### ISSUE TITLE
when click <Preview Email> button. occrs an error.

### ISSUE THREAD

**Issue by hgati** [yireo/Yireo_EmailTester2#13]
when click <Preview Email> button. occrs an error. not found method. on Magento 2.4.6 + php8.2

```
[2023-08-09T07:34:03.770187+00:00] main.CRITICAL: Error: Call to undefined method Magento\Framework\Mail\Template\TransportBuilder\Interceptor::getMessage() in /var/www/magento/vendor/yireo/magento2-emailtester2/Model/Mailer.php:229
Stack trace:
#0 /var/www/magento/vendor/yireo/magento2-emailtester2/Model/Mailer.php(190): Yireo\EmailTester2\Model\Mailer->getRawContentFromTransportBuilder()
#1 /var/www/magento/vendor/yireo/magento2-emailtester2/Block/Adminhtml/Preview.php(68): Yireo\EmailTester2\Model\Mailer->getHtml()
#2 /var/www/magento/vendor/yireo/magento2-emailtester2/Block/Adminhtml/Preview.php(57): Yireo\EmailTester2\Block\Adminhtml\Preview->setMailerOutput()
#3 /var/www/magento/vendor/magento/framework/View/Element/AbstractBlock.php(207): Yireo\EmailTester2\Block\Adminhtml\Preview->_construct()
#4 /var/www/magento/vendor/yireo/magento2-emailtester2/Block/Adminhtml/Preview.php(46): Magento\Framework\View\Element\AbstractBlock->__construct()
#5 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Yireo\EmailTester2\Block\Adminhtml\Preview->__construct()
#6 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#7 /var/www/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#8 /var/www/magento/vendor/magento/framework/View/Element/BlockFactory.php(44): Magento\Framework\ObjectManager\ObjectManager->create()
#9 /var/www/magento/vendor/magento/framework/View/Layout/Generator/Block.php(272): Magento\Framework\View\Element\BlockFactory->createBlock()
#10 /var/www/magento/vendor/magento/framework/View/Layout/Generator/Block.php(252): Magento\Framework\View\Layout\Generator\Block->getBlockInstance()
#11 /var/www/magento/vendor/magento/framework/View/Layout.php(797): Magento\Framework\View\Layout\Generator\Block->createBlock()
#12 /var/www/magento/vendor/magento/framework/View/Layout.php(780): Magento\Framework\View\Layout->_createBlock()
#13 /var/www/magento/vendor/yireo/magento2-emailtester2/Controller/Adminhtml/Index/Preview.php(96): Magento\Framework\View\Layout->createBlock()
#14 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview->execute()
#15 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->___callParent()
#16 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/magento/generated/code/Yireo/EmailTester2/Controller/Adminhtml/Index/Preview/Interceptor.php(23): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->___callPlugins()
#18 /var/www/magento/vendor/magento/framework/App/Action/Action.php(111): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->execute()
#19 /var/www/magento/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#20 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#21 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->___callParent()
#22 /var/www/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#23 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#24 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#25 /var/www/magento/generated/code/Yireo/EmailTester2/Controller/Adminhtml/Index/Preview/Interceptor.php(32): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->___callPlugins()
#26 /var/www/magento/vendor/magento/framework/App/FrontController.php(245): Yireo\EmailTester2\Controller\Adminhtml\Index\Preview\Interceptor->dispatch()
#27 /var/www/magento/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#28 /var/www/magento/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest()
#29 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#30 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#31 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#32 /var/www/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#33 /var/www/magento/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#34 /var/www/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#35 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#36 /var/www/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#37 {main} {"exception":"[object] (Error(code: 0): Call to undefined method Magento\\Framework\\Mail\\Template\\TransportBuilder\\Interceptor::getMessage() at /var/www/magento/vendor/yireo/magento2-emailtester2/Model/Mailer.php:229)"} []
```

**Comment by jissereitsma** [comment]
Thanks for opening an issue. I noticed that you closed the issue right away. Could you please comment on why the issue was opened in the first place and why you closed it again? If there is anything in this extension that could be improved, it would be nice to know.

**Comment by hgati** [comment]
The preview button works correctly on the local development server. However, on the live server, it does not function and is accompanied by the error mentioned above. Due to the overwhelming amount of analysis required, I have closed it.
